### ISSUE TITLE
LLM-generated candidates

### ISSUE THREAD

**Issue by PCguai** [GeorgeVern/lmcor#3]
Hi I am a beginner in NPL and I would like to ask, should I download the dataset myself for example (Xsum) and then input the big model myself to get the output and put it into the train_[llm_name] and validation_[llm_name] file? What should be the format?

**Comment by GeorgeVern** [comment]
Hi, 

thank you for your interest in our work, and apologies for the late response. 
Yes indeed, you should sample the predictions from the big model yourself and then place them in the files `data/xsum/train_[llm_name]`  and `data/xsum/validation_[llm_name]`. You can check [this code](https://github.com/GeorgeVern/qe-fusion/blob/main/llm_inference_utils.py) for reference on sampling from an LLM. 
In our approach we generated two types of outputs from the LLM: one using greedy decoding and another using sampling. The corresponding filenames are indicated by FILE_SAMPLE and FILE_GREEDY in the code, which should give you an idea of how to structure your output files. In each case, we wrote each prediction on a separate line.
